CREATE TABLE foods (id BIGINT AUTO_INCREMENT PRIMARY KEY,
uuid CHAR(36) NOT NULL DEFAULT (uuid()),
food_name VARCHAR(100) NOT NULL,
category VARCHAR(50) NOT NULL,
calories INT,
price DECIMAL(6,2),
available BOOLEAN DEFAULT TRUE,
expiration_date DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL);

