CREATE TABLE foods (id BIGINT AUTO_INCREMENT PRIMARY KEY,
uuid CHAR(36) NOT NULL DEFAULT (uuid()),
food_name VARVCHAR(100) NOT NULL,
category VARCHAR(50) NOT NULL,
calories INT,
price DECIMAL(6,2),
available BOOLEAN DEFAULT TRUE,
expiration_date DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
